/*
 * WAZIUP API
 * This API allows you to access all Waziup services. In order to access protected services, first get a token with POST /auth/token. Then insert this token in the authorization key, specifying \"Bearer\" in front. For example \"Bearer: eyJhbGc...\".
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.apps.waziup.domain.services.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoricalValue
 */

public class HistoricalValue {
    @SerializedName("id")
    private String id = null;

    @SerializedName("attribute_id")
    private String attributeId = null;

    @SerializedName("datapoint")
    private MeasurementValue datapoint = null;

    public HistoricalValue id(String id) {
        this.id = id;
        return this;
    }

    /**
     * UUID of the sensor
     *
     * @return id
     **/
    @ApiModelProperty(example = "0d710b12-27e8-433d-ab3a-e05b7127eeaa", value = "UUID of the sensor")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public HistoricalValue attributeId(String attributeId) {
        this.attributeId = attributeId;
        return this;
    }

    /**
     * UUID of the measurement
     *
     * @return attributeId
     **/
    @ApiModelProperty(example = "0d710b12-27e8-433d-ab3a-e05b7127eeaa", value = "UUID of the measurement")
    public String getAttributeId() {
        return attributeId;
    }

    public void setAttributeId(String attributeId) {
        this.attributeId = attributeId;
    }

    public HistoricalValue datapoint(MeasurementValue datapoint) {
        this.datapoint = datapoint;
        return this;
    }

    /**
     * Get datapoint
     *
     * @return datapoint
     **/
    @ApiModelProperty(value = "")
    public MeasurementValue getDatapoint() {
        return datapoint;
    }

    public void setDatapoint(MeasurementValue datapoint) {
        this.datapoint = datapoint;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HistoricalValue historicalValue = (HistoricalValue) o;
        return Objects.equals(this.id, historicalValue.id) &&
                Objects.equals(this.attributeId, historicalValue.attributeId) &&
                Objects.equals(this.datapoint, historicalValue.datapoint);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, attributeId, datapoint);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class HistoricalValue {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    attributeId: ").append(toIndentedString(attributeId)).append("\n");
        sb.append("    datapoint: ").append(toIndentedString(datapoint)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

