/*
 * WAZIUP API
 * This API allows you to access all Waziup services. In order to access protected services, first get a token with POST /auth/token. Then insert this token in the authorization key, specifying \"Bearer\" in front. For example \"Bearer: eyJhbGc...\".
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.apps.waziup.domain.services.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * MeasurementValue
 */

public class MeasurementValue {
    @SerializedName("value")
    private Float value = null;

    @SerializedName("timestamp")
    private String timestamp = null;

    public MeasurementValue value(Float value) {
        this.value = value;
        return this;
    }

    /**
     * value of the measurement
     *
     * @return value
     **/
    @ApiModelProperty(example = "25.6", value = "value of the measurement")
    public Float getValue() {
        return value;
    }

    public void setValue(Float value) {
        this.value = value;
    }

    public MeasurementValue timestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * time of the measurement
     *
     * @return timestamp
     **/
    @ApiModelProperty(example = "2016-06-08T18:20:27.873Z", value = "time of the measurement")
    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MeasurementValue measurementValue = (MeasurementValue) o;
        return Objects.equals(this.value, measurementValue.value) &&
                Objects.equals(this.timestamp, measurementValue.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value, timestamp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MeasurementValue {\n");

        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

