/*
 * WAZIUP API
 * This API allows you to access all Waziup services. In order to access protected services, first get a token with POST /auth/token. Then insert this token in the authorization key, specifying \"Bearer\" in front. For example \"Bearer: eyJhbGc...\".
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.apps.waziup.domain.services.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * NotificationCondition
 */

public class NotificationCondition {
    @SerializedName("attrs")
    private List<String> attrs = null;

    @SerializedName("expression")
    private String expression = null;

    public NotificationCondition attrs(List<String> attrs) {
        this.attrs = attrs;
        return this;
    }

    public NotificationCondition addAttrsItem(String attrsItem) {
        if (this.attrs == null) {
            this.attrs = new ArrayList<String>();
        }
        this.attrs.add(attrsItem);
        return this;
    }

    /**
     * Get attrs
     *
     * @return attrs
     **/
    @ApiModelProperty(value = "")
    public List<String> getAttrs() {
        return attrs;
    }

    public void setAttrs(List<String> attrs) {
        this.attrs = attrs;
    }

    public NotificationCondition expression(String expression) {
        this.expression = expression;
        return this;
    }

    /**
     * Get expression
     *
     * @return expression
     **/
    @ApiModelProperty(example = "SM1>40", value = "")
    public String getExpression() {
        return expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NotificationCondition notificationCondition = (NotificationCondition) o;
        return Objects.equals(this.attrs, notificationCondition.attrs) &&
                Objects.equals(this.expression, notificationCondition.expression);
    }

    @Override
    public int hashCode() {
        return Objects.hash(attrs, expression);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NotificationCondition {\n");

        sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
        sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

