/*
 * WAZIUP API
 * This API allows you to access all Waziup services. In order to access protected services, first get a token with POST /auth/token. Then insert this token in the authorization key, specifying \"Bearer\" in front. For example \"Bearer: eyJhbGc...\".
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.apps.waziup.domain.services.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserUpdateBody
 */

public class UserUpdateBody {
    @SerializedName("firstName")
    private String firstName = null;

    @SerializedName("lastName")
    private String lastName = null;

    @SerializedName("id")
    private String id = null;

    public UserUpdateBody firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * User&#39;s First Name
     *
     * @return firstName
     **/
    @ApiModelProperty(required = true, value = "User's First Name")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public UserUpdateBody lastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * User&#39;s Last Name
     *
     * @return lastName
     **/
    @ApiModelProperty(required = true, value = "User's Last Name")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public UserUpdateBody id(String id) {
        this.id = id;
        return this;
    }

    /**
     * User id
     *
     * @return id
     **/
    @ApiModelProperty(value = "User id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserUpdateBody userUpdateBody = (UserUpdateBody) o;
        return Objects.equals(this.firstName, userUpdateBody.firstName) &&
                Objects.equals(this.lastName, userUpdateBody.lastName) &&
                Objects.equals(this.id, userUpdateBody.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName, id);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserUpdateBody {\n");

        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

